[Interface]
Address = 10.0.0.1/24
ListenPort = 51820
PrivateKey = <REMOVED>

[Peer]
PublicKey = <PEER1_PUBLIC_KEY>
AllowedIPs = 10.0.0.2/32

[Peer]
PublicKey = <PEER2_PUBLIC_KEY>
AllowedIPs = 10.0.0.3/32

[Peer]
PublicKey = <PEER3_PUBLIC_KEY>
AllowedIPs = 10.0.0.4/32

[Peer]
PublicKey = <PEER4_PUBLIC_KEY>
AllowedIPs = 10.0.0.5/32
