services:
  worker1:
    build:
      context: ..
      dockerfile: docker/worker.Dockerfile
    environment:
      - COORDINATOR_URL=http://10.236.223.107:3000

  worker2:
    build:
      context: ..
      dockerfile: docker/worker.Dockerfile
    environment:
      - COORDINATOR_URL=http://10.236.223.107:3000

