services:

  worker1:
    build:
      context: ..
      dockerfile: docker/worker.Dockerfile
    environment:
      - COORDINATOR_URL=http://10.10.10.1:3000

  worker2:
    build:
      context: ..
      dockerfile: docker/worker.Dockerfile
    environment:
      - COORDINATOR_URL=http://10.10.10.1:3000

  worker3:
    build:
      context: ..
      dockerfile: docker/worker.Dockerfile
    environment:
      - COORDINATOR_URL=http://10.10.10.1:3000

  worker4:
    build:
      context: ..
      dockerfile: docker/worker.Dockerfile
    environment:
      - COORDINATOR_URL=http://10.10.10.1:3000
